### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 3)

### ISSUE THREAD

**Issue by deldesir** [iiab/calibre-web#209]
Regression in the file uploading mechanism causing a ""503 INTERNAL ERROR"

```
Traceback (most recent call last):
  File "/usr/local/calibre-web-py3/cps/editbooks.py", line 452, in meta
    resp = move_mediafile(requested_file, current_user_name, shelf_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/calibre-web-py3/cps/editbooks.py", line 388, in move_mediafile
    (
ValueError: not enough values to unpack (expected 4, got 3)
```

**Comment by holta** [comment]
Somewhat related:

- #107
- PR #207
- PR #208
