### ISSUE TITLE
AttributeError on Response object

### ISSUE THREAD

**Issue by deldesir** [iiab/calibre-web#30]
Weird issue even when the request succeeds:

`Traceback (most recent call last):
File "/usr/local/calibre-web-py3/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/calibre-web-py3/lib/python3.10/site-packages/flask/app.py", line 1487, in full_dispatch_request
return self.finalize_request(rv)
File "/usr/local/calibre-web-py3/lib/python3.10/site-packages/flask/app.py", line 1506, in finalize_request
response = self.make_response(rv)
File "/usr/local/calibre-web-py3/lib/python3.10/site-packages/flask/app.py", line 1851, in make_response
rv.status_code = status
File "/usr/local/calibre-web-py3/lib/python3.10/site-packages/werkzeug/sansio/response.py", line 182, in status_code
self.status = code # type: ignore
File "/usr/local/calibre-web-py3/lib/python3.10/site-packages/werkzeug/sansio/response.py", line 191, in status
self._status, self._status_code = self._clean_status(value)
File "/usr/local/calibre-web-py3/lib/python3.10/site-packages/werkzeug/sansio/response.py", line 197, in _clean_status
value = value.strip()
AttributeError: 'Response' object has no attribute 'strip'`

**Comment by holta** [comment]
@deldesir appears to have figured this out that an upstream (Calibre-Web) change might be involved:

Thanks for posting an explanation and/or PR when you can today if possible!
