### ISSUE TITLE
"Download to IIAB" of Vimeo video ("Staff Pick") does not appear

### ISSUE THREAD

**Issue by holta** [iiab/calibre-web#78]
1) No video was downloaded to `/library/calibre-web` after I clicked on "Download to IIAB" with https://vimeo.com/channels/staffpicks/893773360 :

![image](https://github.com/janeczku/calibre-web/assets/2458907/2569a643-dd99-4f0c-9da1-4218541e7415)

2) Subsequently trying again with equivalent/short URL https://vimeo.com/893773360 led to the exact same result.

Do the diagnostics below help?

```
root@lrn2:/library/downloads/calibre-web# tree
.
├── survey.db
├── survey.db.2023-11-28_12:45:50_CST
├── survey.db.2023-12-24_10:49:40_CST
└── Vimeo
    └── Mattias_Evangelista
        └── Actual_Air_5.53k_[893773360].jpg

2 directories, 4 files
```

```
root@lrn2:/library/downloads/calibre-web# ls -l Vimeo/Mattias_Evangelista/Actual_Air_5.53k_\[893773360\].jpg
-rw-r--r-- 1 root root 110760 Dec 24 10:49 'Vimeo/Mattias_Evangelista/Actual_Air_5.53k_[893773360].jpg'
```

```
root@lrn2:/library/downloads/calibre-web# mediainfo Vimeo/Mattias_Evangelista/Actual_Air_5.53k_\[893773360\].jpg
General
Complete name                            : Vimeo/Mattias_Evangelista/Actual_Air_5.53k_[893773360].jpg
Format                                   : JPEG
File size                                : 108 KiB

Image
Format                                   : JPEG
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Compression mode                         : Lossy
Stream size                              : 108 KiB (100%)
```

```
root@lrn2:~# tail -25 /var/log/calibre-log
[2023-12-24 10:46:51,585] DEBUG {cps.web:1410} You are now logged in as: 'Admin'
[2023-12-24 10:46:51,631] DEBUG {cps.ub:82} Login and store session : 7b51c8cd1a0300222e238fbe082b17560b5df60de619e059735108f54051dc2c033fb410262fb79e726b514223d132e68554a42ff0bd1c630ecc051fe2771fde
[2023-12-24 10:46:51,639] DEBUG {cps.ub:84} Found stored session: 7b51c8cd1a0300222e238fbe082b17560b5df60de619e059735108f54051dc2c033fb410262fb79e726b514223d132e68554a42ff0bd1c630ecc051fe2771fde
[2023-12-24 10:49:40,375] DEBUG {cps.services.worker:91} Add Task for user: Admin - Download https://vimeo.com/channels/staffpicks/893773360
[2023-12-24 10:49:40,377]  INFO {cps.tasks.download:28} Starting download task for URL: https://vimeo.com/channels/staffpicks/893773360
[2023-12-24 10:49:40,377]  INFO {cps.tasks.download:37} Subprocess args: ['lb-wrapper', 'https://vimeo.com/channels/staffpicks/893773360']
[2023-12-24 10:49:40,395]  INFO {cps.tasks.download:50} /usr/local/bin/lb

[2023-12-24 10:49:53,953]  INFO {cps.editbooks:382} Requested files list: ['https://vimeo.com/channels/staffpicks/893773360']
[2023-12-24 10:49:53,954] ERROR {cps:1414} Exception on /meta [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/calibre-web-py3/cps/editbooks.py", line 471, in meta
    if move_mediafile(requested_files, current_user_name, shelf_title):
  File "/usr/local/calibre-web-py3/cps/editbooks.py", line 384, in move_mediafile
    requested_file = open(requested_file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'https://vimeo.com/channels/staffpicks/893773360'
[2023-12-24 10:49:54,045] ERROR {cps.tasks.download:81} Failed to send the list of requested files to https://lrn2.org/live/meta
```

```
root@lrn2:~# tail -4 /var/log/xklb.log
2023-11-28 12:45:57 - An error occurred while running the command. Output:
2023-12-24 10:49:40 - Old /library/downloads/calibre-web/survey.db moved aside.
2023-12-24 10:49:40 - Running command: lb tubeadd /library/downloads/calibre-web/survey.db https://vimeo.com/channels/staffpicks/893773360 --verbose && lb dl /library/downloads/calibre-web/survey.db --prefix /library/downloads/calibre-web --write-thumbnail --format best --format-sort 'tbr~1000' --video https://vimeo.com/channels/staffpicks/893773360 --verbose
2023-12-24 10:49:53 - Download completed successfully.
```

```
root@lrn2:/usr/local/calibre-web-py3# git log --oneline | head
e83c81e5 Merge branch 'janeczku:master' into master
4c64662b README.md: "Internet-in-a-Box does not support Docker"
2f7413cb Merge pull request #75 from deldesir/deldesir-tornado
93791b3a Increase Buffersize to 10GB
25fb8d93 Merge remote-tracking branch 'nl/master'
b456263d Merge pull request #72 from deldesir/deldesir-mp4-cover
525cd2fe Support case insensitive ext
bc0ebdb7 Updated Dutch translation.
cdfd9b31 Merge pull request #71 from deldesir/deldesir-description
04306ba2 Pull description
```

```
root@lrn2:~# cat /etc/issue
Ubuntu 22.04.3 LTS \n \l
```

```
root@lrn2:~# lb --version
2.2.192
```

```
root@lrn2:~# yt-dlp --version
2023.10.13
```

ASIDE: Since then I tried to upgrade yt-dlp...

```
root@lrn2:~# pipx upgrade --include-injected xklb
xklb is already at latest version 2.2.192 (location: /root/.local/pipx/venvs/xklb)
```

That was not sufficient — so in the end `pipx reinstall xklb` did finally force yt-dlp to upgrade...

```
root@lrn2:~# yt-dlp --version
2023.11.16
```

...either way that did not help, when I later tried downloading the same video using its shorter URL https://vimeo.com/893773360 — though with a different failure pattern in `/var/log/calibre-log` :

```
root@lrn2:~# tail -6 /var/log/calibre-log
[2023-12-24 11:37:04,820] DEBUG {cps.services.worker:91} Add Task for user: Admin - Download https://vimeo.com/893773360
[2023-12-24 11:37:04,822]  INFO {cps.tasks.download:28} Starting download task for URL: https://vimeo.com/893773360
[2023-12-24 11:37:04,823]  INFO {cps.tasks.download:37} Subprocess args: ['lb-wrapper', 'https://vimeo.com/893773360']
[2023-12-24 11:37:04,829]  INFO {cps.tasks.download:50} /usr/local/bin/lb

[2023-12-24 11:37:15,284] ERROR {cps.tasks.download:81} Failed to send the list of requested files to https://lrn2.org/live/media?data=root&sort_param=stored
```

```
root@lrn2:~# tail -3 /var/log/xklb.log
2023-12-24 11:37:04 - Old /library/downloads/calibre-web/survey.db moved aside.
2023-12-24 11:37:04 - Running command: lb tubeadd /library/downloads/calibre-web/survey.db https://vimeo.com/893773360 --verbose && lb dl /library/downloads/calibre-web/survey.db --prefix /library/downloads/calibre-web --write-thumbnail --format best --format-sort 'tbr~1000' --video https://vimeo.com/893773360 --verbose
2023-12-24 11:37:15 - Download completed successfully.
```

Possibly related:

- #76
- #77

**Comment by holta** [comment]
FYI the 1st regular YouTube video I tried ("easy 3d drawing on paper for beginner") also fails to download.

```
root@lrn2:~# tail -20 /var/log/calibre-log
[2023-12-24 11:37:15,284] ERROR {cps.tasks.download:81} Failed to send the list of requested files to https://lrn2.org/live/media?data=root&sort_param=stored
[2023-12-24 11:56:09,768] ERROR {cps:1414} Exception on /meta [HEAD]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'edit-book.meta' did not return a valid response. The function either returned None or ended without a return statement.
[2023-12-24 12:02:51,067] DEBUG {cps.services.worker:91} Add Task for user: Admin - Download https://youtu.be/J91zoR53WYo
[2023-12-24 12:02:51,077]  INFO {cps.tasks.download:28} Starting download task for URL: https://youtu.be/J91zoR53WYo
[2023-12-24 12:02:51,081]  INFO {cps.tasks.download:37} Subprocess args: ['lb-wrapper', 'https://youtu.be/J91zoR53WYo']
[2023-12-24 12:02:51,118]  INFO {cps.tasks.download:50} /usr/local/bin/lb

[2023-12-24 12:03:09,220] ERROR {cps.tasks.download:81} Failed to send the list of requested files to https://lrn2.org/live/media?data=root&sort_param=stored
[2023-12-24 12:05:49,412] DEBUG {cps.updater:329} Stable version: {'version': '0.6.22 Beta'}
[2023-12-24 12:06:23,410] DEBUG {cps.config_sql:376} _ConfigSQL updating storage
```

But then then next two worked:
(strangely including "easy 3d drawing on paper for beginner" when it was retried with the exact same URL!)

![image](https://github.com/iiab/calibre-web/assets/2458907/6882d57a-d347-497e-bf29-4309fb636bdd)

Log below shows these 2 latest videos when it  began to work:

```
root@lrn2:~# cat /var/log/calibre-web.log
[2023-12-24 12:06:23,433]  INFO {cps.server:319} webserver stop (restart=True)
[2023-12-24 12:06:23,435]  INFO {apscheduler.scheduler:212} Scheduler has been shut down
[2023-12-24 12:06:24,442]  INFO {cps.server:300} Performing restart of Calibre-Web
[2023-12-24 12:06:27,171]  INFO {cps:168} *** "greenlet" version does not meet the requirements. Should: <2.1.0, Found: 3.0.0, please consider installing required version ***
[2023-12-24 12:06:27,172]  INFO {cps:168} *** "py7zr" version does not meet the requirements. Should: >=0.15.0, Found: 0.11.3+dfsg, please consider installing required version ***
[2023-12-24 12:06:27,172]  INFO {cps:177} Starting Calibre Web...
[2023-12-24 12:06:27,274] DEBUG {cps.services:26} Cannot import goodreads, showing authors-metadata will not work: No module named 'betterreads'
[2023-12-24 12:06:27,279] DEBUG {cps.services:34} Cannot import simpleldap, logging in with ldap will not work: No module named 'flask_simpleldap'
[2023-12-24 12:06:27,283] DEBUG {cps.services:42} Cannot import SyncToken, syncing books with Kobo Devices will not work: No module named 'jsonschema'
[2023-12-24 12:06:27,285] DEBUG {cps.services:49} Cannot import gmail, sending books via Gmail Oauth2 Verification will not work: No module named 'google_auth_oauthlib'
[2023-12-24 12:06:27,343]  WARN {py.warnings:109} /usr/local/calibre-web-py3/lib/python3.10/site-packages/flask_limiter/extension.py:336: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(

[2023-12-24 12:06:27,843] DEBUG {cps.gdriveutils:81} Cannot import pydrive, httplib2, using gdrive will not work: No module named 'pydrive'
[2023-12-24 12:06:28,492]  INFO {apscheduler.scheduler:181} Scheduler started
[2023-12-24 12:06:28,494]  INFO {apscheduler.scheduler:895} Added job "end scheduled task" to job store "default"
[2023-12-24 12:06:28,703] DEBUG {cps.comic:46} Cannot import comicapi, extracting comic metadata will not work: No module named 'comicapi'
[2023-12-24 12:06:28,707] DEBUG {cps.comic:53} Cannot import rarfile, extracting cover files from rar files will not work: No module named 'rarfile'
[2023-12-24 12:06:29,205] DEBUG {cps.admin:81} Cannot import Flask-Dance, login with Oauth will not work: No module named 'flask_dance'
[2023-12-24 12:06:29,214] DEBUG {cps.gdrive:44} Cannot import googleapiclient, using GDrive will not work: No module named 'googleapiclient'
[2023-12-24 12:06:29,356] DEBUG {cps.search_metadata:62} Import error for metadata source: lubimyczytac - No module named 'markdown2'
[2023-12-24 12:06:29,406] DEBUG {cps.search_metadata:62} Import error for metadata source: scholar - No module named 'scholarly'
[2023-12-24 12:06:29,827]  INFO {cps.server:267} Starting Tornado server on :8083
[2023-12-24 12:08:17,789] DEBUG {cps.services.worker:91} Add Task for user: Admin - Download https://youtu.be/_-i_0_h4BF8
[2023-12-24 12:08:17,791]  INFO {cps.tasks.download:28} Starting download task for URL: https://youtu.be/_-i_0_h4BF8
[2023-12-24 12:08:17,792]  INFO {cps.tasks.download:37} Subprocess args: ['lb-wrapper', 'https://youtu.be/_-i_0_h4BF8']
[2023-12-24 12:08:17,799]  INFO {cps.tasks.download:50} /usr/local/bin/lb

[2023-12-24 12:08:30,742]  INFO {cps.editbooks:382} Requested files list: ['/library/downloads/calibre-web/Youtube/Sylcom_Light/Rare_Artistry_Enrich_Your_Soul_with_the_Relaxing_Craft_of_Venetian_Glass_Art_Design_Sylcom_Light_3.48M_[_-i_0_h4BF8].mp4']
[2023-12-24 12:08:30,743]  INFO {cps.editbooks:388} Processing file: <_io.BufferedReader name='/library/downloads/calibre-web/Youtube/Sylcom_Light/Rare_Artistry_Enrich_Your_Soul_with_the_Relaxing_Craft_of_Venetian_Glass_Art_Design_Sylcom_Light_3.48M_[_-i_0_h4BF8].mp4'>
[2023-12-24 12:08:30,744] DEBUG {cps.uploader:371} Temporary file: /tmp/calibre_web/1d2f9af545641118a90b8321983c97b1
[2023-12-24 12:08:31,071] DEBUG {cps.helper:543} Moving title: /tmp/calibre_web/1d2f9af545641118a90b8321983c97b1 to /library/calibre-web/Sylcom Light/Rare Artistry Enrich Your Soul with the Relaxing Craft of Venetian Glass Art Design Sylcom Light (250)/Rare Artistry Enrich Your Soul with the Relaxing Craft of Venetian Glass Art Design Sylcom Light - Sylcom Light
[2023-12-24 12:08:31,089] DEBUG {cps.services.worker:91} Add Task for user: Admin - Upload Rare Artistry Enrich Your Soul with the Relaxing Craft of Venetian Glass Art Design Sylcom Light
[2023-12-24 12:08:31,096]  INFO {cps.tasks.download:79} Successfully sent the list of requested files to https://lrn2.org/live/meta
[2023-12-24 12:09:01,209] DEBUG {cps.services.worker:91} Add Task for user: Admin - Download https://youtu.be/J91zoR53WYo
[2023-12-24 12:09:01,210]  INFO {cps.tasks.download:28} Starting download task for URL: https://youtu.be/J91zoR53WYo
[2023-12-24 12:09:01,211]  INFO {cps.tasks.download:37} Subprocess args: ['lb-wrapper', 'https://youtu.be/J91zoR53WYo']
[2023-12-24 12:09:01,218]  INFO {cps.tasks.download:50} /usr/local/bin/lb

[2023-12-24 12:09:12,579]  INFO {cps.editbooks:382} Requested files list: ['/library/downloads/calibre-web/Youtube/draw/easy_3d_drawing_on_paper_for_beginner_5.61M_[J91zoR53WYo].mp4']
[2023-12-24 12:09:12,581]  INFO {cps.editbooks:388} Processing file: <_io.BufferedReader name='/library/downloads/calibre-web/Youtube/draw/easy_3d_drawing_on_paper_for_beginner_5.61M_[J91zoR53WYo].mp4'>
[2023-12-24 12:09:12,582] DEBUG {cps.uploader:371} Temporary file: /tmp/calibre_web/8a6fd59aa12b0d919c64f42fcd5812d7
[2023-12-24 12:09:12,720] DEBUG {cps.helper:543} Moving title: /tmp/calibre_web/8a6fd59aa12b0d919c64f42fcd5812d7 to /library/calibre-web/draw/easy 3d drawing on paper for beginner (251)/easy 3d drawing on paper for beginner - draw
[2023-12-24 12:09:12,730] DEBUG {cps.services.worker:91} Add Task for user: Admin - Upload easy 3d drawing on paper for beginner
[2023-12-24 12:09:12,736]  INFO {cps.tasks.download:79} Successfully sent the list of requested files to https://lrn2.org/live/meta
```

RECAP:

```
root@lrn2:/library/downloads/calibre-web# tree
.
├── survey.db
├── survey.db.2023-11-28_12:45:50_CST
├── survey.db.2023-12-24_10:49:40_CST
├── survey.db.2023-12-24_11:34:58_CST
├── survey.db.2023-12-24_11:37:04_CST
├── survey.db.2023-12-24_12:02:51_CST
├── survey.db.2023-12-24_12:08:17_CST
├── survey.db.2023-12-24_12:09:01_CST
├── Vimeo
│   ├── Benign_Delusion
│   │   └── Two_Chairs_Not_One_4.66k_[895977355].jpg
│   └── Mattias_Evangelista
│       ├── Actual_Air_5.53k_[893773360].jpg
│       └── Actual_Air_5.54k_[893773360].jpg
└── Youtube
    ├── draw
    │   └── easy_3d_drawing_on_paper_for_beginner_5.61M_[J91zoR53WYo].mp4
    └── Sylcom_Light
        └── Rare_Artistry_Enrich_Your_Soul_with_the_Relaxing_Craft_of_Venetian_Glass_Art_Design_Sylcom_Light_3.48M_[_-i_0_h4BF8].mp4

6 directories, 13 files
```

**Comment by EMG70** [comment]
Ten vimeo short videos downloaded successively and all showed on homepage.
A second attempt was made to download all 10 urls at once and successfully downloaded after 4mins.

screenshots for the 10 batch download:
https://vimeo.com/101260809
https://vimeo.com/125696078
https://vimeo.com/218538912
https://vimeo.com/22030635
https://vimeo.com/222470400
https://vimeo.com/241673906
https://vimeo.com/245466297
https://vimeo.com/381271095
https://vimeo.com/452371533
https://vimeo.com/9582297

![Screenshot from 2023-12-27 15-07-05](https://github.com/iiab/calibre-web/assets/52469992/af6c9364-bfb4-446f-b8a6-ee1dbc7c3f83)
![Screenshot from 2023-12-27 15-11-08](https://github.com/iiab/calibre-web/assets/52469992/dc0a0b7b-dfde-4451-be85-c8942194f13a)
![Screenshot from 2023-12-27 15-15-24](https://github.com/iiab/calibre-web/assets/52469992/a7ee0e7a-63ca-465b-b45c-a99729c0d3a3)

iiab-diagnostics http://sprunge.us/TP4J9q?en

pastebinit -b sprunge.us /var/log/calibre-web.log
http://sprunge.us/taqvIe?en
pastebinit -b sprunge.us /var/log/xklb.log
http://sprunge.us/uD5CWo?en

**Comment by EMG70** [comment]
Ten vimeo short videos downloaded successively and all showed on on homepage.
A second attempt was made to download al 10 urls at once and successfully downloaded after 4mins.
screenshots for the 10 batch download:
https://vimeo.com/101260809
https://vimeo.com/125696078
https://vimeo.com/218538912
https://vimeo.com/22030635
https://vimeo.com/222470400
https://vimeo.com/241673906
https://vimeo.com/245466297
https://vimeo.com/381271095
https://vimeo.com/452371533
https://vimeo.com/9582297

Screenshot from 2023-12-27 15-07-05
![Screenshot from 2023-12-27 15-07-05](https://github.com/iiab/calibre-web/assets/52469992/ab14420a-2170-4352-9b1d-28f727e2caaa)
![Screenshot from 2023-12-27 15-11-08](https://github.com/iiab/calibre-web/assets/52469992/e88f0eba-867b-46c2-af24-9eacb59bb450)
![Screenshot from 2023-12-27 15-15-24](https://github.com/iiab/calibre-web/assets/52469992/701a24f8-706d-44db-ad7f-10515897dfb9)

iiab-diagnostics  http://sprunge.us/TP4J9q?en
pastebinit -b sprunge.us /var/log/calibre-web.log
http://sprunge.us/taqvIe?en
pastebinit -b sprunge.us /var/log/xklb.log
http://sprunge.us/uD5CWo?en
